### ISSUE TITLE
Tafel wordt ineens een locatie.

### ISSUE THREAD

**Issue by HarmenTulner** [otech-nl/adventure#11]
Je bent in de keuken.
bekijk keuken
een ruimte om te koken en te eten
Er liggen hier: tafel

Je bent in de keuken.
ga tafel
'tafel is vanuit keuken niet te bereiken'

**Comment by DiederickKaaij** [comment]
Dit is dezelfde issue als issue #6

**Comment by otech-nl** [comment]
Klopt. Tafel is een object, geen locatie.
