### ISSUE TITLE
Spelfout beschrijving hal

### ISSUE THREAD

**Issue by DiederickKaaij** [otech-nl/adventure#3]
Als in locatie Hal
Doe 'bekijk hal'
Dan krijgen we "een ruimte die andere ruimtes met elkaar vebindt"
Moet "verbindt" zijn

**Comment by Lasharus** [comment]
Neem ik wel over en fix ik. (Jelmer hier, i.v.m. username :P )

**Comment by otech-nl** [comment]
Sorry, ik had 'm zelf al gezien en gefixt.
