### ISSUE TITLE
Woonkamer sleutel onbereikbaar

### ISSUE THREAD

**Issue by DiederickKaaij** [otech-nl/adventure#7]
Er ligt een mooie sleutel in de woonkamer, maar als we in de woonkamer komen winnen we automatisch, dus de sleutel is momenteel onbereikbaar om mee te interacteren.

**Comment by sixmatom** [comment]
ik pak deze op

**Comment by otech-nl** [comment]
Ik zou zeggen dat dit een fout is in de data, en niet zozeer in de engine. Eens?

**Comment by DiederickKaaij** [comment]
Eens, ik sluit hem. Geen fout van de engine.
